version: '3'

networks:
  symfony1:

services:

  symfony1-nginx:
    image: nginx:stable
    container_name: symfony1-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony1-php
      - symfony1-mysql
    networks:
      - symfony1

  symfony1-php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony1-php
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - symfony1

  symfony1-mysql:
    image: mysql:8
    container_name: symfony1-mysql
    ports:
      - "3306:33061"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - symfony1
